fail_fast: true                     # stop on first error
repos:
-   repo: local
    hooks:
    -   id: lint-language
        name: allowed
        entry: ./allowed.sh
        language: system
        pass_filenames: false
        types: [python]

    -   id: test
        name: pytest
        entry: uv run pytest        # command line options are in pyproject.toml
        language: system
        pass_filenames: false       # run pytest on all files
        types: [python]             # run pytest only if a Python file changed

    -   id: typecheck
        name: ty
        entry: uv run ty check
        language: system
        pass_filenames: false
        types: [python]

    # ruff hooks were adapted from https://github.com/astral-sh/ruff-pre-commit
    -   id: lint
        name: ruff-check
        entry: uv run ruff check --force-exclude
        language: system
        types_or: [python, pyi]
        require_serial: true

    -   id: format
        name: ruff-format
        entry: uv run ruff format --force-exclude
        language: system
        types_or: [python, pyi]
        require_serial: true

    -   id: docs
        name: pdoc
        entry: uv run pdoc -o docs paddles
        language: system
        pass_filenames: false
        types: [python]
