repos:
-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        # the command line options are in pyproject.toml
        entry: poetry run pytest
        language: system
        # run pytest on all files
        pass_filenames: false
        # run pytest only if a Python file changed
        types: [python]