fail_fast: true                     # stop on first error
repos:
-   repo: local
    hooks:
    -   id: test
        name: pytest
        entry: poetry run pytest    # command line options are in pyproject.toml
        language: system
        pass_filenames: false       # run pytest on all files
        types: [python]             # run pytest only if a Python file changed

    -   id: typecheck
        name: pytype
        entry: poetry run pytype .
        language: system
        pass_filenames: false
        types: [python]

    # the following was adapted from https://github.com/astral-sh/ruff-pre-commit
    -   id: lint
        name: ruff-check
        entry: poetry run ruff check --force-exclude
        language: system
        types_or: [python, pyi]
        require_serial: true

    -   id: format
        name: ruff-format
        entry: poetry run ruff format --force-exclude
        language: system
        types_or: [python, pyi]
        require_serial: true
